### PR TITLE
Add Python 3.8 and 3.9 to .travis.yml

### PR DESCRIPTION
**Pull request by eumiro**
Do you consider moving to GitHub Actions and dropping support for Python 2.7, 3.4, 3.5 (all of them after EOL)?

### CODE REVIEW

**Comment by cecton** [comment]
I think it would be good yes! I don't mind doing the conversion to GH actions if nobody wants to do it. But I'm not the owner anymore, I will let @jruere decides

**Comment by cecton** [comment]
Oh great and Travis CI broke again so it didn't trigger the PR builds :sweat: one more reason to move to GH Actions

**Comment by cecton** [comment]
Found this: https://github.com/actions/setup-python

**Comment by eumiro** [comment]
Yes, it should work in GHA quite well, even without the ubuntu repository hacks (the `ubuntu-latest` offers a recent enough version of `libmagic1`). I just wanted to ask before PR.

**Comment by eumiro** [comment]
As soon as GHA in #16 works, this can be closed and `.travis.yml` removed.

**Comment by jruere** [comment]
I've never used GitHub Actions. Lets me understand it and I'll merge.
@cecton , if you understand it and the PR is good, feel free to merge it.

**Comment by cecton** [comment]
@jruere now you have a CI Export :tm: :grin:

**Comment by eumiro** [comment]
Since we're going to adopt GHA in #16 (with Python 3.6–3.9) and I would love to drop support for Python up to 3.5, I'll close this PR and remove `.travis.yml` entirely when we see that GHA works well.

**Pull request closed without merging**
